"""Remove tags column and add Tag model with many-to-many relationship

Revision ID: 5944ebf23737
Revises: dd6037e23ebb
Create Date: 2025-04-18 10:00:29.624119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5944ebf23737'
down_revision = 'dd6037e23ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
