"""Added problems stuffs

Revision ID: 703027c87b69
Revises: 7dd75b2501a8
Create Date: 2025-04-23 11:26:29.574605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703027c87b69'
down_revision = '7dd75b2501a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
