"""added comments stuffs

Revision ID: 7dd75b2501a8
Revises: 5944ebf23737
Create Date: 2025-04-22 11:14:28.010235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd75b2501a8'
down_revision = '5944ebf23737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_comments')
    op.drop_table('_alembic_tmp_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_title', sa.VARCHAR(length=150), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=300), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts_comments',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'comment_id')
    )
    # ### end Alembic commands ###
